### ISSUE TITLE
Errors on Main.py, api.py, and pubg.py after last update.

### ISSUE THREAD

**Issue by Sunn91** [kragebein/pubg.reportbot#3]
Hello,

Since last update I am receiving couple errors (using python 3.6 and 3.7). 

> `1|pubgrepo |   File "/home/ubuntu/pubg.reportbot/bot/main.py", line 212, in on_message
> 
>  1|pubgrepo |     api.event(report_id, message.author)
> 
>  1|pubgrepo |   File "/home/ubuntu/pubg.reportbot/bot/pubg.py", line 51, in event
> 
>  1|pubgrepo |     self.build_embed(discorduser=discorduser, killer=killer, victim=victim, distance=distance, mmap=mmap,  mode=mode, weapon=weapon, event=event, twitchID=twitchID, videoID=videoID, matchID=matchID, eventID=eventID, when=when, diff=diff)
> 
>  1|pubgrepo |   File "/home/ubuntu/pubg.reportbot/bot/main.py", line 154, in build_embed
> 
>  1|pubgrepo |     about = compute(victim=victim, matchid=matchID)
> 
>  1|pubgrepo |   File "/home/ubuntu/pubg.reportbot/bot/api.py", line 35, in compute
> 
>  1|pubgrepo |     for i in proc['included']:
> 
>  1|pubgrepo | KeyError: 'included'`
> 
> `1|pubgrepo |   File "/home/ubuntu/pubg.reportbot/bot/main.py", line 141, in build_embed
> 
> 1|pubgrepo |     embed.set_author(name=discorduser.split('#')[0])
> 
> 1|pubgrepo | AttributeError: 'Member' object has no attribute 'split'`

Bot is online on discord channel but it's not sending messages with reports. But when I use "!test <nickname>" it is uploading last reports. I tried with python 3.6 and 3.7 and still same. Discord.py is up to date. I am not sure if it's something with API/bot or I screwed up installation.

If it's important I am running bot with pm2.
![putty_S11nq0UB0O222](https://user-images.githubusercontent.com/36042067/94323521-774e0300-ff96-11ea-9198-76633e55e65a.png)

Regards.

**Comment by kragebein** [comment]
Hi, i just pushed a new version, could you try the latest please?

**Comment by Sunn91** [comment]
Hello,

Unfortunately still get these errors.
![puttypoakt](https://user-images.githubusercontent.com/36042067/94335558-bef77d80-ffdc-11ea-807e-81f6c9c60f9a.png)

**Comment by kragebein** [comment]
What version of discordpy are you running?

**Comment by kragebein** [comment]
Try deleting the database file and restarting the bot. Did you register anything using the @discordname handle ?

**Comment by Sunn91** [comment]
I deleted database but still errors...

> Did you register anything using the @DiscordName handle ?

You mean nickname from discord or for example "@nick"? No, only nicknames from PUBG (!register <nick from game>).

**Comment by Sunn91** [comment]
Okay, I think I found something weird I mean I launched bot manually from command (python3.7 pubgbot.py) and it was uploading reports. But there were still these errors from topic. So it looks like maybe I screwed up pm2 configuration or bot is not working with pm2.

![asd](https://user-images.githubusercontent.com/36042067/94343944-2385fd00-001c-11eb-8d1e-d646f8ab5633.png)

EDIT:
Okay, my bad. It was working only for while. My !test reports were uploaded, but no more. 
![222](https://user-images.githubusercontent.com/36042067/94351868-9748f980-005e-11eb-93f3-3920acafd8bd.png)

Is this possible that nicknames with symbols like "_", "-" (for example "TL_Ibiza", "ATC_Marcelek" are crashing something?

EDIT2:
Hmmm it's getting more complicated xd here's steps which I made after clearing database once again:
1. register my nickname 
2. run !test - received errors but reports were uploaded
3. My friend added his nickname and made !test- received errors and reports were not uploaded 
4. After 15-20min reports of my friend were uploaded.
![444](https://user-images.githubusercontent.com/36042067/94352421-20fbc580-0065-11eb-939a-53f53006a0cc.png)

PS. Sorry for spam but I am a little bit confused what is going on.

Regards.

**Comment by kragebein** [comment]
Hi, sorry for the slow response, been busy.  

I'm honestly not sure what is going on.  The Bot is written specifically for 3.6, and that could possibly cause this? Maybe? I don't really know. The problem isnt with pubg api or pubg.report, this is a discord issue. 
You are getting a member object in return when what you should get is the handle of the user for whom its reporting these for. 
once that breaks, the bot wont publish because it couldnt continue. 

if you are able to, comment out line 141 of build_embed() in the file main.py. Does that fix the issue?

**Comment by Sunn91** [comment]
Hello,

No problem! 

> if you are able to, comment out line 141 of build_embed() in the file main.py. Does that fix the issue?

I'll try to do that. But there is possibility that everything is okay with bot - these errors probably not affecting on uploading reports. After some tests, I found that bot is connected to the channel all the time (pm2 script to keep it's alive) but it's uploading reports only when I am connected to my AWS instance by PuTTY. Yesterday I did not close connected putty for whole day and it was fine. 

Is it possible that it's not working without connecting by putty because I did not set up autorestart bot script after every 5-10mins?

**Comment by kragebein** [comment]
I'm not sure why that might be.  As long as the script is running, it SHOULD be doing stuff all the time. I dont know what pm2 is really, but is it possible that AWs does something weird when you disconnect?

You could try to just start the bot using a screen or tmux session

**Comment by Sunn91** [comment]
> is it possible that AWs does something weird when you disconnect?

No, that was my second thought that maybe AWS instance is hibernating or sth. But from AWS side it was OK.

> You could try to just start the bot using a screen or tmux session

And it looks like screen is working ;) Since yesterday no more problems with not uploaded reports. I don't know why PM2/forever does not kept script working all the time. 
PS. ot is no longer posting an image of the map?

Thank You for help and sorry for a little mess!

**Comment by kragebein** [comment]
Unknown member bug in build_embed(), discord.Member returned Member insead of handle.

**Comment by kragebein** [comment]
Leaving bug open, need to figure this out at some point

**Comment by kragebein** [comment]
@Sunn91 , yes, i've removed image of the map to clean up the layout of the embed. Some had maps and some didnt. 
But did you ever remove that line I asked you about?  I need to know if was the removal of that line, or you just swapping over to screen that made it work

**Comment by Sunn91** [comment]
> But did you ever remove that line I asked you about? 

Before I used the screen, yes. It did not change anything. To be sure what was the solution firstly I commented this line and when it not helped, did clean install on instance and start the bot with Screen (and then it started working as it should).

Now bot is working without any ingerention since tuesday. These errors apparently do not affect its operation.

![putty_pYuPDL0NSS](https://user-images.githubusercontent.com/36042067/94787185-41fc4780-03d2-11eb-9f20-151672b457ed.png)

**Comment by stevestokes** [comment]
I am getting the same issue on the split() function. 
`embed.set_author(name=discorduser.split('#')[0] if '.' in discorduser else discorduser)`

I was able to fix this by modifying it to
`embed.set_author(name=discorduser)`

However, the full discord name with number now appears `MyCoolPubgName#1234.`

The error I see is 
```
  File "C:\pubg.reportbot\bot\main.py", line 142, in build_embed
    embed.set_author(name=discorduser.split('#')[0] if '.' in discorduser else discorduser)
TypeError: argument of type 'User' is not iterable
```

It's possible discord.py made User an object and now the split command is trying to split on an object and not a string? I tried to set the discorduser = some string var then split but did not have any luck....but I'm also a Py noob.



Unrelated I also had to update this line-
`weapon = weapons_list[weapon]`
to
`weapon = 'N/A' if weapon=='' else weapons_list[weapon]`

Because some weapons were coming back as null from the pubg.report api
